Notifica-Web/Notifica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # root url "/" is for classroom app
    url(r'^', include('classroom.urls', namespace="classroom")),

    # /classroom is used for mobile urls
    url(r'^classroom/', include('classroom.mobile_urls')),
]

Notifica-Web/classroom/urls.py
from django.conf.urls import patterns, url
from classroom import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.index, name='home'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^student/$', views.student, name='student'),
    url(r'^user_settings/$', views.user_settings, name='user_settings'),

    url(r'^authority/$', views.authority, name='authority'),
    url(r'^authority/(?P<batch>\d+)/$', views.authority, name='authority'),
    url(r'^authority/routine/$', views.routine, name='routine'),
    url(r'^authority/routine/(?P<routine_id>\d+)/$', views.routine, name='routine'),

 #    url(r'^delete/$', views.delete, name='delete'),
 #    url(r'^set_post_seen/$', views.set_post_seen, name='set_post_seen'),

    url(r'^teacher/$', views.teacher, name='teacher'),

#     url(r'^sql/$', views.sql, name='sql'),
)

Notifica-Web/classroom/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import *

Notifica-Web/classroom/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from datetime import datetime

from django.db.models import Q
from .models import *
from .mobile_views import DeletePassed, GetUser
from .forms import *
from .sqlgenerator import GetAllSql
from helpers import hm_to_int

from collections import defaultdict

def redirect_user(user):
    tp, obj = GetUser(user)
    if tp == "Teacher":
        return redirect('classroom:teacher')
    elif tp == "Student":
        return redirect('classroom:student')
    elif tp == "Authority":
        return redirect('classroom:authority')
    else:
        return None

# def sql(request):
#     return HttpResponse(GetAllSql(), content_type="text/plain")

def index(request):
    context = {}
    if request.user.is_authenticated():
        redir = redirect_user(request.user)
        if redir is not None:
            return redir

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                redir = redirect_user(user)
                if redir is not None:
                    return redir
        try:
            User.objects.get(username=username)
            context = {"wrong_password":True, "username":username}
        except:
            context = {"wrong_username":True}

    return render(request, 'classroom/index.html', context)

def user_settings(request):
    context = {}
    return render(request, 'classroom/user_settings.html', context)

def change_password(request):
    user = request.user
    context = {'oldpass':request.POST.get("oldpass"), "newpass":request.POST.get("newpass"), "renewpass":request.POST.get("renewpass")}
    if not user.is_authenticated():
        return {}
    if not user.check_password(context["oldpass"]):
        context.update({'wrong_password':True})
        return context
    if context["newpass"] != context["renewpass"]:
        context.update({'wrong_retype_password':True})
        return context

    user.set_password(context["newpass"])
    user.save()
    return {'password_changed':True}

# def delete(request):
#     if request.method != "POST":
#         return redirect('classroom:index')
#     if not request.user.is_authenticated():
#         return HttpResponse('')
# 
#     # TODO: check privilege
# 
#     if request.POST.get("type") == "assignment":
#         assignment = Assignment.objects.get(pk=request.POST.get("pk"))
#         assignment.cancelled = True
#         assignment.save()
#     elif request.POST.get("type") == "notice":
#         notice = Notice.objects.get(pk=request.POST.get("pk"))
#         notice.cancelled = True
#         notice.save()
#     return HttpResponse('')
# 
# def set_post_seen(request):
#     if request.method != "POST":
#         return redirect('classroom:index')
#     if not request.user.is_authenticated():
#         return HttpResponse('')
# 
#     UnseenNotice.objects.filter(user=request.user, notice__pk=request.POST.get("pk")).delete()
#     return HttpResponse('')
# 
# 
# def post_assignment(request):
#     context = {"date":request.POST.get("date"), "subject":request.POST.get("subject"), "group":request.POST.get("group"),
#                "summary":request.POST.get("summary"), "details":request.POST.get("details"), "pinned":request.POST.get("pinned")}
#     if not request.user.is_authenticated():
#         return {}
# 
#     assignment = Assignment()
# 
#     user_type, user = GetUser(request.user)
#     if user_type == "Student":
#         assignment.faculty = user.faculty
#         assignment.batch = user.batch
#     elif user_type == "Teacher":
#         context.update({"faculty":request.POST.get("faculty"), "batch":request.POST.get("batch")})
#         assignment.faculty = Faculty.objects.get(code=context["faculty"])
#         assignment.batch = context["batch"]
# 
#     assignment.groups = "" if context["group"] == "All" else context["group"]
#     assignment.poster = request.user
#     assignment.subject = Subject.objects.get(code=context["subject"])
#     assignment.summary = context["summary"]
#     assignment.details = context["details"]
#     assignment.date = context["date"] if not context["pinned"] else None
#     assignment.save()
# 
#     return {'assignment_posted':True}

# def post_notice(request):
#     context = {"date":request.POST.get("date"), "group":request.POST.get("group"),
#                "summary":request.POST.get("summary"), "details":request.POST.get("details")}
#     if not request.user.is_authenticated():
#         return {}
# 
#     notice = Notice()
# 
#     user_type, user = GetUser(request.user)
#     if user_type == "Student":
#         notice.faculty = user.faculty
#         notice.batch = user.batch
#     elif user_type == "Teacher":
#         context.update({"faculty":request.POST.get("faculty"), "batch":request.POST.get("batch")})
#         notice.faculty = Faculty.objects.get(code=context["faculty"])
#         notice.batch = context["batch"]
# 
#     notice.groups = "" if context["group"] == "All" else context["group"]
#     notice.poster = request.user
#     notice.summary = context["summary"]
#     notice.details = context["details"]
#     notice.date = context["date"] if context["date"] != "" else None
#     notice.save()
# 
#     return {'notice_posted':True}


def get_sections(class_):
    sections = []
    ss = class_.section_set.all()
    for s in ss:
        sections.append(s.code)
    return sections

def get_notices_assignments(notices):
    ns = []
    ass = []
    for n in notices:
        try:
            x = n.assignment
            ass.append(n.assignment)
        except:
            ns.append(n)
    return ns, ass

def student(request):
    if not request.user.is_authenticated():
        return redirect('classroom:index')

    try:
        user = Student.objects.get(user=request.user)
    except:
        return redirect('classroom:index')

    context = {}
    # if request.method == "POST":
    #     if 'post_assignment' in request.POST:
    #         context.update(post_assignment(request))
    #     elif 'post_notice' in request.POST:
    #         context.update(post_notice(request))
    #     elif 'change_password' in request.POST:
    #         context.update(change_password(request))
    #     return redirect('classroom:student')

    DeletePassed()

    elements_objects = RoutineSlot.objects.filter(sections=user.section).order_by('start_time')
    notices_objects = Notice.objects.filter(sections=user.section, cancelled = False).order_by('-modified_at')
    notices_objects, assignments_objects = get_notices_assignments(notices_objects)

    courses = set()
    for element in elements_objects:
        courses.add(element.course)

    workingweek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    routine = {}

    last_element = {}

    initial_time = None

    for loopcount, elem in enumerate(elements_objects):
        if initial_time == None or hm_to_int(initial_time) > hm_to_int(elem.start_time):
             initial_time = elem.start_time

        if elem.day in last_element:
            elem.gap = hm_to_int(elem.start_time) - hm_to_int(last_element[elem.day].end_time)
            elem.prevelem = last_element[elem.day]
            last_element[elem.day].nextelem = elem
        else:
            elem.gap = hm_to_int(elem.start_time) - hm_to_int(initial_time)

        last_element[elem.day] = elem
        elem.duration = hm_to_int(elem.end_time) - hm_to_int(elem.start_time)
        routine[loopcount] = elem

    # static daily routine
    daily_routine = defaultdict(list)
    for i, element in routine.items():
        daily_routine[element.day].append(element)


    daily_routine.default_factory = None

    context["unseen_notices"] = UnseenNotice.objects.filter(user=user.user, notice__cancelled=False).values_list('notice',flat=True)

    names = user.name.split(' ')
    context.update({'user':user, 'routine':routine, 'notices':notices_objects, 'assignments':assignments_objects,
                    'workingweek':workingweek, 'firstname':names[0],
                    'courselist':list(courses), 'grouplist':get_sections(user.section.pclass), 'daily_routine':daily_routine })
    return render(request, 'classroom/student.html', context)


def teacher(request):
    if not request.user.is_authenticated():
        return redirect('classroom:index')

    try:
        user = Teacher.objects.get(user=request.user)
    except:
        return redirect('classroom:index')

    context = {}
    if request.method == "POST":
        if 'post_assignment' in request.POST:
            context.update(post_assignment(request))
        elif 'post_notice' in request.POST:
            context.update(post_notice(request))
        elif 'change_password' in request.POST:
            context.update(change_password(request))
        return redirect('classroom:teacher')

    DeletePassed()

    elements_objects = RoutineElement.objects.filter(teachers__pk=user.pk).order_by('start_time')
    assignments_objects = Assignment.objects.filter(poster=user.user, cancelled = False).order_by('-modified_at')
    events_objects = Notice.objects.filter(poster=user.user, cancelled = False).order_by('-modified_at')
    attendances_objects = Attendance.objects.filter(teacher=user).order_by('-date')

    subjects = set()
    batches = set()
    faculties = set()
    for element in elements_objects:
        subjects.add(element.subject)
        faculties.add(element.routine.faculty)
        batches.add(element.routine.batch)

    workingweek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

Notifica-Web/classroom/templates/classroom/authority/routines.html
<div id="routines" class="tab-pane fade">
    <div class="container">
        <div class="row text-center">
            <h2 class="page-title title-routines">Routines</h2>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <select class="select-batch pull-left" onchange="location=this.options[this.selectedIndex].value + '#routines';">
                    {%if batch == null %}
                    <option value="#" selected="selected">Select a batch</option>
                    {%endif%}
                    {%for a_batch in batches %}
                        {% if batch|stringformat:"s" == a_batch|stringformat:"s" %}
                        <option value="{% url 'classroom:authority' a_batch %}" selected="selected">{{a_batch}}</option>
                        {%else%}
                        <option value="{% url 'classroom:authority' a_batch %}">{{a_batch}}</option>
                        {% endif %}
                    {%endfor%}
                </select>
            </div>
            <div class="col-sm-4">
                <a class="btn btn-add pull-right" href="{% url 'classroom:routine' %}"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <div class="row">
            {% if batch %}
                {% for routine in routines %}
                    <hr style="color:#ccc; border:1px solid;">
                    <div class="row">
                        <div class="col-md-6"><h3 class="title-group pull-left">Group: {{routine.groups}} </h3></div>
                        <div class="col-md-6">
                            <a class="btn btn-sm btn-success btn-edit-routine pull-right" href="{% url 'classroom:routine' routine.pk %}"><i class="fa fa-pencil-square-o"></i> Edit</a>
                        </div>
                    </div>
                    <div class="row">
                        {% for a_day in workingweek %}
                            <div class="col-md-2 day">
                                <h3 > {{ a_day }} </h3>
                                {% for element in routine.elements %}
                                    {% if element.day == forloop.parentloop.counter0  %}
                                        <div class="list-group list-group-routines">
                                            <div class="list-group-item list-group-item-routines">
                                                <p class="list-group-item-text"><strong>{{element.subject}}</strong></p>
                                                <p class="list-group-item-text"><small>{{element.teachers.all|join:', '}}</small></p>
                                                <p class="list-group-item-text"><small>{{element.start_time}} to {{element.end_time}}</small></p>
                                                {% if element.class_type == 0 %}
                                                    <p class ="list-group-item-text"><small>(Lecture)</small></p>
                                                {% else %}
                                                    <p class ="list-group-item-text"><small>(Practical)</small></p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            {%else%}
                <div class="list-group-item list-group-item-empty">
                    <p>Select a batch to view the routines</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>

Notifica-Web/classroom/templates/classroom/authority/students.html
<div id="students" class="tab-pane active">
    <div class="container">
        <div class="row text-center">
            <h2 class="page-title title-students">Students</h2>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <select class="select-batch pull-left" onchange="location=this.options[this.selectedIndex].value + '#students';">
                    {%if batch == null %}
                    <option value="#" selected="selected">Select a batch</option>
                    {%endif%}
                    {%for a_batch in batches %}
                        {% if batch|stringformat:"s" == a_batch|stringformat:"s" %}
                        <option value="{% url 'classroom:authority' a_batch %}" selected="selected">{{a_batch}}</option>
                        {%else%}
                        <option value="{% url 'classroom:authority' a_batch %}">{{a_batch}}</option>
                        {% endif %}
                    {%endfor%}
                </select>
            </div>
            <div class="col-sm-4">
                <a class="btn btn-add pull-right" data-toggle="collapse" data-target="#form-add-student"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8 collapse-group">
                {% if student_error %} <p class="text-danger">{{ student_error }}</p> {% endif %}
                <form class="form collapse form-add-student" method="post" name="add-student" id="form-add-student">
                    {% csrf_token %}
                    <div class="row control-group">
                        <h3> Add Student </h3>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Name" id="name" required>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-md-5 floating-label-form-group controls">
                            <label>Roll</label>
                            <input type="number" name="roll" class="form-control" placeholder="Roll No." id="roll"
                                    {% if roll %} value="{{roll|add:'1'}}" {% endif %} required>
                        </div>
                        <div class="form-group col-md-offset-2 col-md-5 floating-label-form-group controls">
                            <label>Group</label>
                            <input type="text" name="group" class="form-control" placeholder="Group" id="group" value="{{group}}" required>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-md-5 floating-label-form-group controls">
                            <label>Batch</label>
                            <input type="number" name="batch" class="form-control" placeholder="Batch" id="batch" value="{{batch}}" required>
                        </div>
                        <div class="form-group col-md-5 col-md-offset-2">
                            <div class="checkbox chekbox-representative">
                                <label><input name="is_representative" type="checkbox"> Representative</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <button name="add_student" type="submit" class="btn btn-success btn-lg"><i class="fa fa-plus"></i> Add</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="list-group list-group-students">
                    {% if batch and students%}
                    {% for student in students %}
                        {% if not forloop.counter|divisibleby:2 %}
                        <div class="row row-list-group-item">
                        {%endif%}
                        <div class="col-sm-6">
                            <div class="list-group-item list-group-item-students">
                                <p>{{student.roll}}. <strong>{{ student.name }}</strong> </p>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:2 or students|length == forloop.counter %}
                        </div>
                        {%endif%}

                    {% endfor %}

                    {%else%}
                    <div class="list-group-item list-group-item-empty">
                        {% if batch %}
                            <p>No student has been added yet</p>
                        {% else %}
                            <p>Select a batch to get the list of students</p>
                        {% endif %}
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>

Notifica-Web/classroom/templates/classroom/authority/subjects.html
<div id="subjects" class="tab-pane fade">
    <div class="container">
        <div class="row text-center">
            <h2 class="page-title title-subjects">Subjects</h2>
        </div>
        <div class="row">
            <a class="btn btn-add pull-right" data-toggle="collapse" data-target="#form-add-subject"><i class="fa fa-plus"></i></a>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8 collapse-group">
                {% if subject_error %} <p class="text-danger">{{ subject_error }}</p> {% endif %}
                <form class="form collapse form-add-subject"method="post" name="form-add-subject" id="form-add-subject">
                    {% csrf_token %}
                    <div class="row control-group">
                        <h3>Add Subject</h3>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Name of Subject" id="name">
                        </div>
                    </div>
                    <div class="row control-group ">
                        <div class="col-xs-12 select-group">
                            <label>Department: </label>
                            <select class="select-faculty" name="faculty" id="faculty" >
                                <option value="current">{{user.faculty.name}}</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <button name="add_subject" type="submit" class="btn btn-success btn-lg"><i class="fa fa-plus"></i> Add</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="list-group list-group-subjects">
                    {% if subjects %}
                    {% for subject in subjects %}
                        {% if not forloop.counter|divisibleby:2 %}
                        <div class="row row-list-group-item">
                        {%endif%}
                        <div class="col-sm-6">
                            <div class="list-group-item list-group-item-subjects">
                                <p><strong>{{ subject.name }}</strong> </p>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:2 or forloop.last %}
                        </div>
                        {%endif%}
                    {% endfor %}
                    {%else%}
                    <div class="list-group-item list-group-item-empty">
                        <p>No subject has been added yet</p>
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>

Notifica-Web/classroom/templates/classroom/authority/teachers.html
<div id="teachers" class="tab-pane fade">
    <div class="container">
        <div class="row text-center">
            <h2 class="page-title title-teachers">Teachers</h2>
        </div>
        <div class="row">
            <a class="btn btn-add pull-right" data-toggle="collapse" data-target="#form-add-teacher"><i class="fa fa-plus"></i></a>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8 collapse-group">
                {% if teacher_error %} <p class="text-danger">{{ teacher_error }}</p> {% endif %}
                <form class="form collapse form-add-teacher" method="post" name="form-add-teacher" id="form-add-teacher">
                    {% csrf_token %}
                    <div class="row control-group">
                        <h3>Add Teacher</h3>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Name" id="name" {% if teacher_error %}value="{{teacher_name}}"{% endif %}>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Username</label>
                            <input type="text" name="username" class="form-control" placeholder="Username" id="username" {% if teacher_error %}value="{{username}}"{% endif %}>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Password</label>
                            <input type="text" name="password" class="form-control" placeholder="Password" id="password">
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 controls select-group">
                            <label>Department:</label>
                            <select class="select-faculty">
                                <option value="current">{{user.faculty.name}}</option>
                                <option value="other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <button name="add_teacher" type="submit" class="btn btn-success btn-lg"><i class="fa fa-plus"></i> Add</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8">
                <div class="list-group list-group-subjects">
                    {% if teachers %}
                    {% for teacher in teachers %}
                        {% if not forloop.counter|divisibleby:2 %}
                        <div class="row row-list-group-item">
                        {%endif%}
                        <div class="col-sm-6">
                            <div class="list-group-item list-group-item-teachers">
                                <p><strong>{{ teacher.name }}</strong> </p>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:2 or forloop.last %}
                        </div>
                        {%endif%}
                    {% endfor %}
                    {%else%}
                    <div class="list-group-item list-group-item-empty">
                        <p>No teacher has been added yet</p>
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>